version: "3.7"

services:
  currency-exchange-service:
    image: sundalei/msv2-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - currency-network
    environment:
      - SERVER_PORT=8000
      - MYSQL_URL=jdbc:mysql://mysqlserver/udemy_spring_cloud
      - EUREKA_CLIENT_SERVICE_URL=http://netflix-eureka-naming-server:8761/eureka
    restart: always
    depends_on:
      - netflix-eureka-naming-server

  netflix-eureka-naming-server:
    image: sundalei/msv2-netflix-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network
    restart: always

  mysqlserver:
    image: mariadb:10.8.3
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mypassword
      - MYSQL_DATABASE=udemy_spring_cloud
    networks:
      - currency-network
    restart: always

networks:
  currency-network:
