spring:
  application:
    name: currency-conversion-service
  sleuth:
    sampler:
      probability: 1.0

server:
  port: ${SERVER_PORT:8100}
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}