spring:
  application:
    name: currency-conversion-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://localhost:9411/}
    sender:
      type: ${ZIPKIN_SENDER_TYPE:rabbit}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}

server:
  port: ${SERVER_PORT:8100}
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}