server:
  port: 8000

spring:
  application:
    name: currency-exchange-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: root
    password: mypassword
    url: jdbc:mysql://localhost/udemy_spring_cloud
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka