spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: mypassword
    url: jdbc:mysql://localhost/udemy_spring_cloud

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/