server:
  port: 8000

spring:
  application:
    name: currency-exchange-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: mypassword
    url: jdbc:mysql://localhost/udemy_spring_cloud