spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password: Fnst*1234
    url: jdbc:mysql://localhost/test

server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/