server:
  port: ${SERVER_PORT:8000}

spring:
  application:
    name: currency-exchange-service
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: ${MYSQL_USER:sa}
    password: ${MYSQL_PASS:password}
    url: ${H2_URL:jdbc:h2:mem:testdb}
  sleuth:
    sampler:
      probability: 1.0

resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5
        wait-duration: 5s
        enable-exponential-backoff: true
  circuitbreaker:
    instances:
      default:
        failure-rate-threshold: 90
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
